seeds_file = "/home/cycle/ahc/015/tools/2000_seeds.txt"
input_folder = "/home/cycle/ahc/015/tools/2000_in"
output_folder = "/home/cycle/ahc/015/evaluation/2000_out"
vis_folder = "/home/cycle/ahc/015/evaluation/2000_vis"

[executable_files]
submission = "/home/cycle/ahc/015/target/release/submission"
vis = "/home/cycle/ahc/015/target/release/vis"
