[paths]
seeds_file = "/home/cycle/ahc/016/tools/seeds_100.txt"
input_dir = "/home/cycle/ahc/016/tools/in"
output_dir = "/home/cycle/ahc/016/evaluation/out_100"

[paths.executable_files]
submission = "/home/cycle/ahc/016/target/release/submission"
tester = "/home/cycle/ahc/016/target/release/tester"

[thread]
thread_num = 16
